#docker-composeで使用するバージョン
version: '3.8'

# dbデータの保存場所。(ホストからは見えない)
volumes:
  mysql-data:

services:
 #サービスの名前
  centos:
    build: .
    ports:
    - 8181:81
    - 8182:82
    - 8183:83
    - 8184:84
    - 8185:85
    - 8186:86
    - 8187:87
    - 8190:90
    - 8191:91
    - 28000:8000
    - 28001:8001
    - 28002:8002
    - 28003:8003
    - 28004:8004
    - 6001:6001
    volumes:
    - ./html:/var/www/html:cached
    - mysql-data:/var/lib/mysql
    working_dir: /var/www/html
    tty: true
    platform: linux/x86_64
    privileged: true  
    command: /sbin/init

